-- 11_share_token_expiry (issue #172 / SEC-3r residual) — share links expire.
--
--   · Project.shareTokenExpiresAt DateTime? — when the CURRENT share token
--     dies. Additive + nullable per the house rule (zero data migration,
--     nothing dropped or rewritten).
--
-- GRANDFATHERING POLICY (documented, deliberate):
--   · NULL = a token minted BEFORE this migration (pre-existing rows, and
--     seeds, which still lean on the schema's cuid() default). Those links
--     keep the historical never-expires contract — expiring them on deploy
--     would silently cut off every diaspora client mid-build. They pick up a
--     real TTL the moment an owner rotates the link (share.regenerate stamps
--     now + SHARE_TOKEN_TTL_DAYS, default 90), which also invalidates the
--     old token immediately (the existing revocation semantics).
--   · NOT NULL = every token minted after this migration: project creation
--     (POST /api/projects) and share.regenerate both stamp
--     shareTokenExpiresAt = now + SHARE_TOKEN_TTL_DAYS (env knob, default
--     90 days; see .env.example).
--   · Enforcement lives at the token-lookup seam (src/backend/lib/share-token.ts):
--     an expired token is indistinguishable from an unknown one (same 404 /
--     401 the route already answers with — no oracle).
ALTER TABLE "Project" ADD COLUMN "shareTokenExpiresAt" DATETIME;
