import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/backend/lib/db'
import { getProjectPayload, getProjectsList } from '@/backend/lib/mjengo'
import { withGuard } from '@/backend/lib/guard'

export const dynamic = 'force-dynamic'

/** Phase templates: [name, pct of total budget]. */
const TEMPLATES: Record<string, Array<[string, number]>> = {
  bungalow: [
    ['Site Prep & Foundation', 25],
    ['Walling', 20],
    ['Roofing', 15],
    ['Plumbing & Electrical', 15],
    ['Finishing', 25],
  ],
  maisonette: [
    ['Site Prep & Foundation', 20],
    ['Structural Frame', 20],
    ['Walling', 15],
    ['Roofing', 10],
    ['Plumbing & Electrical', 15],
    ['Finishing', 20],
  ],
  duplex: [
    ['Site Prep & Foundation', 22],
    ['Walling', 22],
    ['Roofing', 14],
    ['Plumbing & Electrical', 16],
    ['Finishing', 26],
  ],
  blank: [['Phase 1', 100]],
}

export const GET = withGuard(async (_req, session) => {
  try {
    const projects = await getProjectsList()
    // Client-role sessions see exactly their own project — never the portfolio.
    const scoped =
      session.user.role === 'client' && session.user.projectId
        ? projects.filter((p) => p.id === session.user.projectId)
        : projects
    return NextResponse.json({ ok: true, projects: scoped })
  } catch (e) {
    console.error('[api/projects GET]', e)
    return NextResponse.json({ error: 'Failed to list projects' }, { status: 500 })
  }
})

interface CreateProjectBody {
  name?: string
  client?: string
  clientType?: string
  location?: string
  budget?: number
  startDate?: string
  targetDate?: string
  template?: string
}

export const POST = withGuard(async (req) => {
  try {
    const body = (await req.json()) as CreateProjectBody
    const name = typeof body.name === 'string' ? body.name.trim() : ''
    if (!name) return NextResponse.json({ error: 'name required' }, { status: 400 })
    const budget = Number(body.budget)
    if (!isFinite(budget) || budget <= 0) return NextResponse.json({ error: 'budget must be a positive number' }, { status: 400 })
    const clientType = ['diaspora', 'local', 'company'].includes(body.clientType ?? '')
      ? (body.clientType as string)
      : 'diaspora'
    const template = body.template && body.template in TEMPLATES ? body.template : 'blank'

    const startDate = body.startDate ? new Date(body.startDate) : new Date()
    const defaultTarget = new Date()
    defaultTarget.setDate(defaultTarget.getDate() + 120)
    const targetDate = body.targetDate ? new Date(body.targetDate) : defaultTarget

    // shareToken is generated by the DB default (cuid)
    const project = await db.project.create({
      data: {
        name,
        client: body.client?.trim() || 'New Client',
        clientType,
        location: body.location?.trim() || 'Kenya',
        budget,
        startDate,
        targetDate,
        status: 'active',
      },
    })

    const phaseDefs = TEMPLATES[template]
    for (let i = 0; i < phaseDefs.length; i++) {
      const [phaseName, pct] = phaseDefs[i]
      await db.phase.create({
        data: {
          projectId: project.id,
          name: phaseName,
          order: i + 1,
          budget: Math.round((pct / 100) * budget),
          status: 'pending',
        },
      })
    }

    const [data, projects] = await Promise.all([getProjectPayload(project.id), getProjectsList()])
    return NextResponse.json({ ok: true, result: { id: project.id, shareToken: project.shareToken }, data, projects })
  } catch (e) {
    console.error('[api/projects POST]', e)
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Failed to create project' }, { status: 500 })
  }
}, { roles: ['contractor', 'admin'] })
