import { NextResponse } from 'next/server'
import { db } from '@/backend/lib/db'
import { getProjectPayload, getProjectsList } from '@/backend/lib/mjengo'
import { route, safeError, genericError } from '@/backend/lib/route-kit'

// Projects list + create — src/app/api/projects/route.ts is the shim.

/** Phase templates: [name, pct of total budget]. */
const TEMPLATES: Record<string, Array<[string, number]>> = {
  bungalow: [
    ['Site Prep & Foundation', 25],
    ['Walling', 20],
    ['Roofing', 15],
    ['Plumbing & Electrical', 15],
    ['Finishing', 25],
  ],
  maisonette: [
    ['Site Prep & Foundation', 20],
    ['Structural Frame', 20],
    ['Walling', 15],
    ['Roofing', 10],
    ['Plumbing & Electrical', 15],
    ['Finishing', 20],
  ],
  duplex: [
    ['Site Prep & Foundation', 22],
    ['Walling', 22],
    ['Roofing', 14],
    ['Plumbing & Electrical', 16],
    ['Finishing', 26],
  ],
  blank: [['Phase 1', 100]],
}

export const GET = route(
  { scope: 'api/projects GET', onError: genericError(500, 'Failed to list projects') },
  async (_req, session) => {
    const projects = await getProjectsList()
    // Client-role sessions see exactly their own project — never the portfolio.
    const scoped =
      session.user.role === 'client' && session.user.projectId
        ? projects.filter((p) => p.id === session.user.projectId)
        : projects
    return NextResponse.json({ ok: true, projects: scoped })
  },
)

interface CreateProjectBody {
  name?: string
  client?: string
  clientType?: string
  location?: string
  budget?: number
  startDate?: string
  targetDate?: string
  template?: string
}

export const POST = route(
  {
    scope: 'api/projects POST',
    roles: ['contractor', 'admin'],
    // Rate limit (S-SEC): 10 creates/min — each create writes a project + its
    // phase rows + a full payload build.
    rateLimit: { bucket: 'projects.create', limit: 10, windowMs: 60_000 },
    body: { onParseError: 'throw' },
    onError: safeError(500, 'Failed to create project'),
  },
  async (_req, _session, body) => {
    const parsed = body as CreateProjectBody
    const name = typeof parsed.name === 'string' ? parsed.name.trim() : ''
    if (!name) return NextResponse.json({ error: 'name required' }, { status: 400 })
    if (name.length > 200) return NextResponse.json({ error: 'name must be at most 200 characters' }, { status: 400 })
    for (const [field, value, max] of [
      ['client', parsed.client, 120],
      ['location', parsed.location, 120],
    ] as const) {
      if (value !== undefined && (typeof value !== 'string' || value.length > max)) {
        return NextResponse.json({ error: `${field} must be a string of at most ${max} characters` }, { status: 400 })
      }
    }
    const budget = Number(parsed.budget)
    if (!isFinite(budget) || budget <= 0) return NextResponse.json({ error: 'budget must be a positive number' }, { status: 400 })
    const clientType = ['diaspora', 'local', 'company'].includes(parsed.clientType ?? '')
      ? (parsed.clientType as string)
      : 'diaspora'
    const template = parsed.template && parsed.template in TEMPLATES ? parsed.template : 'blank'

    // Unparseable dates reach Prisma as Invalid Date (S-SEC: its validation
    // error leaks internals) — reject them with an honest 400 instead.
    const invalidDate = (v: string | undefined) => v !== undefined && Number.isNaN(new Date(v).getTime())
    if (invalidDate(parsed.startDate) || invalidDate(parsed.targetDate)) {
      return NextResponse.json(
        { error: `startDate/targetDate must be valid dates (got ${JSON.stringify(parsed.startDate ?? parsed.targetDate)})` },
        { status: 400 },
      )
    }
    const startDate = parsed.startDate ? new Date(parsed.startDate) : new Date()
    const defaultTarget = new Date()
    defaultTarget.setDate(defaultTarget.getDate() + 120)
    const targetDate = parsed.targetDate ? new Date(parsed.targetDate) : defaultTarget

    // shareToken is generated by the DB default (cuid)
    const project = await db.project.create({
      data: {
        name,
        client: parsed.client?.trim() || 'New Client',
        clientType,
        location: parsed.location?.trim() || 'Kenya',
        budget,
        startDate,
        targetDate,
        status: 'active',
      },
    })

    const phaseDefs = TEMPLATES[template]
    for (let i = 0; i < phaseDefs.length; i++) {
      const [phaseName, pct] = phaseDefs[i]
      await db.phase.create({
        data: {
          projectId: project.id,
          name: phaseName,
          order: i + 1,
          budget: Math.round((pct / 100) * budget),
          status: 'pending',
        },
      })
    }

    const [data, projects] = await Promise.all([getProjectPayload(project.id), getProjectsList()])
    return NextResponse.json({ ok: true, result: { id: project.id, shareToken: project.shareToken }, data, projects })
  },
)
