-- 18_upload_confirm_object_key (issue #159 / audit API-8) —
-- POST /api/upload/confirm becomes idempotent on the natural key.
--
-- THE PROBLEM: confirm is step 2 of presign → client PUT → confirm, the
-- S3/R2 deployment surface where retries are EXPECTED (that is why the
-- presign family exists). A retried confirm ran db.attachment.create
-- unconditionally — two Attachment rows pointing at one object, duplicated
-- evidence in the append-only corpus.
--
-- THE DESIGN CHOICE (documented per the issue's "pick the honest design"):
-- the NATURAL-KEY route, not the #177 IdempotencyRecord seam.
--   · withIdempotency (wallet/http.ts) is check-then-act keyed on a
--     CALLER-CHOSEN header key; confirm has no caller-chosen key — its
--     natural key is the server-minted object key itself.
--   · The seam cannot make the create safe under concurrency: both racing
--     requests run their run() (both mint a row) before either writes the
--     record — the record-create collision is swallowed, not prevented.
--     Only a DB unique constraint makes "concurrent double-confirm → one
--     row" true (the issue's explicit AC).
--   · The constraint lives WITH the data it guards; the side-table record
--     can drift (pruning, a crash between row and record write).
--
-- WHY A NEW COLUMN, NOT storageKey (the issue's literal suggestion):
-- Attachment.storageKey records publicUrl(key), which on s3-compat WITHOUT
-- S3_PUBLIC_BASE is a presigned GET minted per call (fresh X-Amz-Date, the
-- SigV4 7-day maximum — pinned in storage-presign-routes.test.ts) — two
-- confirms of the same object seconds apart produce two DIFFERENT
-- storageKey strings, so a unique index there would silently fail to
-- dedupe exactly on private-bucket deployments. The RAW object key
-- (upp-<ts>-<hex>.<ext>) is the true natural key: server-minted per
-- presign response, handed to exactly one session, stable across drivers
-- and deployment configs. It is stored only in fileName today — a display
-- string the document mode fills with user-chosen names — so it gets its
-- own dedicated nullable column, set ONLY by the confirm flow.
--
-- WHY SINGLE-COLUMN UNIQUE (not (objectKey, uploadedBy)): presign keys are
-- minted per response and returned to exactly one session — they are not
-- designed to be shared (the issue's "(storageKey, uploadedBy) if shared
-- keys are legal" clause does not apply). One object = one row; the first
-- confirm wins uploadedBy provenance; a cross-session confirm of the same
-- key implies key leakage, outside this design's threat model, and the
-- replay answer (row id + public fields) leaks nothing.
--
-- WHY NO DEDUPE PASS (the issue's "existing duplicates" clause): the
-- keyspace is NEW — every pre-migration row has objectKey NULL, and SQLite
-- unique indexes skip NULLs, so the constraint cannot trip on legacy data
-- by construction. Historical duplicate rows, if any exist in dev DBs,
-- are left untouched (append-only evidence posture); the constraint guards
-- every confirm from migration time forward. A confirm of a pre-migration
-- key simply mints the first objectKey-bearing row for it.
--
-- Additive-only (house rule): one column + one index, nothing else touched.

-- AlterTable
ALTER TABLE "Attachment" ADD COLUMN "objectKey" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Attachment_objectKey_key" ON "Attachment"("objectKey");
